### ISSUE TITLE
Balloon mod issues.

### ISSUE THREAD

**Issue by eros71-dev** [eros71-dev/sm64ex-coop-mods#1]
Here's a list of issues with this mod:
- Balloons are still not networked properly.
- Balloons aren't despawned after a player leaves the level.
- Some levels glitch the localPlayer's balloon pos.

TODO:
- Fix balloons:
- Fix PVP.
- Force a different camera when using the balloon?
- Fix cannons?

**Comment by eros71-dev** [comment]
ok everything is breaking apart in the game what

**Comment by AgentXLP** [comment]
coop moment
