### ISSUE TITLE
[False Alarm.. but maybe..] GTA SA Mission Passed

### ISSUE THREAD

**Issue by danylopez123** [eros71-dev/sm64ex-coop-mods#3]
I was going to say that the mission passed mod doesnt work the notify when someone gets a star, but turns out, only works in the same map where a player is but sometimes it doesnt play the jingle when someone got a star and the music remains in silence before playing again.

**Comment by eros71-dev** [comment]
To be honest I'm not sure on why that may happen, but if I ever figure it out, I'll fix it, thanks for reporting the issue!
